# Generated by Django 2.0.3 on 2018-04-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='static/image/foot.jpg', upload_to='users/%Y/%m/%d'),
        ),
    ]
